version: "3.9"

services:
  product-ms:
    image: sarptom/federation-orders-ms:latest
    environment:
      - NODE_ENV=development
    restart: always

  orders-ms:
    image: sarptom/federation-orders-ms:latest
    environment:
      - NODE_ENV=development
    restart: always

  users-ms:
    image: sarptom/federation-users-ms:latest
    environment:
      - NODE_ENV=development
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./liquidbase/createdb.sql:/opt/sql
    ports:
      - 5432:5432
  kafka:
    image: kafka

  zookeeper:
    image: zookeeper

  federation-router:
    image: federation-router
